import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :aegis, AegisWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Temporarily enable info logging for debugging
config :logger, level: :error

# Production configuration for smart pagination
config :aegis, :smart_pagination,
  # Analytics enabled by default in production
  analytics_enabled: true,
  # Longer retention in production
  analytics_retention_days: 90,
  # Standard decay values for production workloads
  usage_decay_hours: 48,
  recency_decay_hours: 2

# libcluster configuration for distributed production
# Uses Gossip strategy with multicast for local node discovery
config :libcluster,
  topologies: [
    aegis_cluster: [
      strategy: Cluster.Strategy.Gossip,
      config: [
        # Port for gossip communication
        port: 45892,
        # Multicast address for node discovery
        if_addr: {0, 0, 0, 0},
        # Multicast group
        multicast_addr: {230, 1, 1, 251},
        # How often to broadcast (milliseconds)
        broadcast_period: 2_000,
        # Consider node down after this many missed heartbeats
        secret: "aegis_cluster_secret"
      ]
    ]
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
