defmodule Aegis.Repo.Migrations.AddValidatedField do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:mcp_clients) do
      add :validated, :boolean, null: false, default: false
    end

    drop_if_exists unique_index(:mcp_clients, [:name], name: "mcp_clients_unique_name_index")

    create unique_index(:mcp_clients, [:name, :validated],
             name: "mcp_clients_unique_validated_name_index",
             where: "(validated = true)"
           )
  end

  def down do
    drop_if_exists unique_index(:mcp_clients, [:name, :validated],
                     name: "mcp_clients_unique_validated_name_index"
                   )

    create unique_index(:mcp_clients, [:name], name: "mcp_clients_unique_name_index")

    alter table(:mcp_clients) do
      remove :validated
    end
  end
end
