defmodule Aegis.Repo.Migrations.DropAllowedOriginsFromClients do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:servers) do
      modify :api_key_template, :text, default: "{API_KEY}"
    end

    alter table(:mcp_clients) do
      remove :allowed_origins
    end
  end

  def down do
    alter table(:mcp_clients) do
      add :allowed_origins, {:array, :text}, default: []
    end

    alter table(:servers) do
      modify :api_key_template, :text, default: "Bearer {API_KEY}"
    end
  end
end
