defmodule Aegis.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:servers) do
      remove :encrypted_oauth_client_secret
      remove :oauth_scopes
      remove :oauth_token_url
      remove :oauth_client_id
    end

    alter table(:mcp_clients) do
      remove :oauth_scopes
      remove :oauth_grant_types
      remove :oauth_issuer_url
      remove :oauth_client_id
      remove :auth_type
    end
  end

  def down do
    alter table(:mcp_clients) do
      add :auth_type, :text, null: false, default: "api_key"
      add :oauth_client_id, :text
      add :oauth_issuer_url, :text
      add :oauth_grant_types, {:array, :text}
      add :oauth_scopes, {:array, :text}, default: []
    end

    alter table(:servers) do
      add :oauth_client_id, :text
      add :oauth_token_url, :text
      add :oauth_scopes, {:array, :text}, default: []
      add :encrypted_oauth_client_secret, :binary
    end
  end
end
